server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cstjts0gph6c739fgmg0-a.oregon-postgres.render.com:5432/banco_41fp
        username: banco_41fp_user
        password: VoAASo1ppz5mfT8thnAUem1j2nESz9Px
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
